name: egg_timer
description: Egg Timer

version: 1.0.1+2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fluttery_dart2: ^0.0.9
  intl:
  audioplayers: ^0.13.2
  flutter_local_notifications: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/boop.mp3
    - assets/dingdingding.wav
    - assets/pip.mp3

  fonts:
    - family: AvenirLTStd-Black
      fonts:
        - asset: assets/fonts/AvenirLTStd-Roman.otf

    - family: Releway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf

    - family: SourceHans
      fonts:
        - asset: assets/fonts/SourceHanSansCN-Regular.ttf
