name: egg_timer
description: Egg Timer

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fluttery_dart2: ^0.0.9
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
